export { default as WelcomeScreen } from './WelcomeScreen';
export { default as SignUpScreen } from './SignUpScreen';
export { default as SignInScreen } from './SignInScreen';
export { default as MainScreen } from './MainScreen';
export { default as UploadScreen } from './UploadScreen';
export { default as IdeaScreen } from './IdeaScreen';
export { default as AddCommentScreen } from './AddCommentScreen';
export { default as EditIdeaScreen } from './EditIdeaScreen';
export { default as EditProfileScreen } from './EditProfileScreen';
